### ISSUE TITLE
[CallerFilePath] gets compiled into the library, causing exception when not on author's system

### ISSUE THREAD

**Issue by kaiaverkvist** [TobySalusky/MonoGameHtml#2]
![image](https://user-images.githubusercontent.com/36230927/176936545-9b90b668-3353-421d-9fce-386f04ae468e.png)

**Comment by TobySalusky** [comment]
Ah! That's embarrassing! I didn't realize that would be an issue, since before the NuGet release, I had only built it from source—it seems [CallerFilePath] bakes in the path from which it is built... 

I have made some changes on both the Github (and NuGet, which is now at 1.0.1-alpha) to remove the use of [CallerFilePath]. It should hopefully work now. Let me know if you have any problems with the new release.
